### ISSUE TITLE
Unable to rebase symbolic links / symlinks / sym links

### ISSUE THREAD

**Issue by kendegemaro** [charleso/git-cc#103]
Hello Charles,

First of all, thank you for providing this great OSS-tool to work with, there is nothing comparable out there. I have created my own fork already and made some modifications there to port it to Windows and to adjust it to my needs.

One issue remains for me: ClearCase symbolic link files are not being resolved by git-cc and, as a result, not rebased into my Git repository. This makes it difficult for me to check out certain git commits from the past and make them run, because some very important files are missing. (Related to #100 by @hexcoder- )

Do you intend to implement symlink support in near future? If not, could you please give me a short summary on how you'd implement this logic into git-cc so I can do it on my fork?

Thanks in advance!

**Comment by charleso** [comment]
@kendegemaro Firstly, thanks so much for the kind words! It's a bit sad it's still the only tool that exists.

Symlinks are/were always the hardest problem to solve because they didn't return useful version data from `lshistory` like normal files. I had all sorts of specific hackery to try and guess/find the version of the symlink at the time of a change. It's clearly still not right though. :(

My apologies though, I'm afraid I haven't used/touched this tool in 10 years. There might be other's using this tool, but at least me (the author) isn't going to be much help. :(

Best of luck!
